name: Auto generate PR branches

on:
  # TODO: Remove this push rule
  push:
    branches:
      - 'master'
  schedule:
    # At 02:30 on Saturday
    - cron:  '30 2 * * 6'

jobs:

  generate_pr_branches:

    name: Auto generate PR branches
    runs-on: ubuntu-latest

    steps:
    # Fetch shallow git repository
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check .gitignore in all plugin folders
      if: success() || failure()
      run: ./.github/workflow_scripts/process_any_updated_plugins.sh
      shell: bash